character_images = {
    "Adam Warlock": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Adam%20Warlock%20Deluxe%20Avatar.png",
    "Black Panther": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Black%20Panther%20Deluxe%20Avatar.png",
    "Black Widow": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Black%20Widow%20Deluxe%20Avatar.png",
    "Bruce Banner": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Bruce%20Banner%20Deluxe%20Avatar.png",
    "Captain America": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Captain%20America%20Deluxe%20Avatar.png",
    "Cloak & Dagger": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Cloak%20&amp;%20Dagger%20Deluxe%20Avatar.png",
    "Cloak": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Cloak%20Deluxe%20Avatar.png",
    "Dagger": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Dagger%20Deluxe%20Avatar.png",
    "Doctor Strange": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Doctor%20Strange%20Deluxe%20Avatar.png",
    "Groot": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Groot%20Deluxe%20Avatar.png",
    "Hawkeye": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Hawkeye%20Deluxe%20Avatar.png",
    "Hela": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Hela%20Deluxe%20Avatar.png",
    "Hero Hulk": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Hero%20Hulk%20Deluxe%20Avatar.png",
    "Human Torch": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Human%20Torch%20Deluxe%20Avatar.png",
    "Invisible Woman": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Invisible%20Woman%20Deluxe%20Avatar.png",
    "Iron Fist": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Iron%20Fist%20Deluxe%20Avatar.png",
    "Iron Man": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Iron%20Man%20Deluxe%20Avatar.png",
    "Jeff the Land Shark": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Jeff%20the%20Land%20Shark%20Deluxe%20Avatar.png",
    "Loki": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Loki%20Deluxe%20Avatar.png",
    "Luna Snow": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Luna%20Snow%20Deluxe%20Avatar.png",
    "Magik": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Magik%20Deluxe%20Avatar.png",
    "Magneto": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Magneto%20Deluxe%20Avatar.png",
    "Mantis": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Mantis%20Deluxe%20Avatar.png",
    "Mister Fantastic": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Mister%20Fantastic%20Deluxe%20Avatar.png",
    "Monster Hulk": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Monster%20Hulk%20Deluxe%20Avatar.png",
    "Moon Knight": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Moon%20Knight%20Deluxe%20Avatar.png",
    "Namor": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Namor%20Deluxe%20Avatar.png",
    "Peni Parker": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Peni%20Parker%20Deluxe%20Avatar.png",
    "Psylocke": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Psylocke%20Deluxe%20Avatar.png",
    "Rocket Raccoon": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Rocket%20Raccoon%20Deluxe%20Avatar.png",
    "Scarlet Witch": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Scarlet%20Witch%20Deluxe%20Avatar.png",
    "Spider-Man": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Spider-Man%20Deluxe%20Avatar.png",
    "Squirrel Girl": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Squirrel%20Girl%20Deluxe%20Avatar.png",
    "Star-Lord": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Star-Lord%20Deluxe%20Avatar.png",
    "Storm": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Storm%20Deluxe%20Avatar.png",
    "The Punisher": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/The%20Punisher%20Deluxe%20Avatar.png",
    "The Thing": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/The%20Thing%20Deluxe%20Avatar.png",
    "Thor": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Thor%20Deluxe%20Avatar.png",
    "Venom": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Venom%20Deluxe%20Avatar.png",
    "Winter Soldier": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Winter%20Soldier%20Deluxe%20Avatar.png",
    "Wolverine": "https://rivalskins.com/wp-content/uploads/marvel-assets/assets/lord-icons/Wolverine%20Deluxe%20Avatar.png"
}
