ultimate_lines = {
    "Born Again!": "Adam Warlock",
    "Tremble Before Bast!": "Black Panther",
    "Plasma Burst!": "Black Widow",
    "Assemble!": "Captain America",
    "Us Against the World!": "Cloak & Dagger",
    "By the Eye of Agamotto!": "Doctor Strange",
    "I Am Groot!": "Groot",
    "I Never Miss!": "Hawkeye",
    "Hel Unleashed!": "Hela",
    "Hulk Smash!": "Hero Hulk",
    "I'm Hulking Out!": "Hero Hulk",
    "Supernova!": "Human Torch",
    "Disappear!": "Invisible Woman",
    "Qiguanchanghong!": "Iron Fist",
    "Maximum Pulse!": "Iron Man",
    "Nom Nom!": "Jeff the Land Shark",
    "Your Powers Are Mine!": "Loki",
    "I'm Ready to Put on a Show!": "Luna Snow",
    "Behold, Darkchild!": "Magik",
    "Fear Magneto!": "Magneto",
    "We Are Undefeatable!": "Mantis",
    "Fantastic!": "Mister Fantastic",
    "The Moon Haunts You!": "Moon Knight",
    "Horn Blast": "Namor",
    "It's Spider-Time!": "Peni Parker",
    "Chō No Mai o Kurae!": "Psylocke",
    "Judge, Jury, Executioner!": "The Punisher",
    "This Is Real Firepower": "Rocket Raccoon",
    "Pure Chaos!": "Scarlet Witch",
    "Squirrel Stampede!": "Squirrel Girl",
    "Don't Mess With the Amazing Spider-Man!": "Spider-Man",
    "Legendary!": "Star-Lord",
    "Feel the Wrath of the Goddess": "Storm",
    "It's Clobberin’ Time!": "The Thing",
    "Behold, the God of Thunder!": "Thor",
    "We Are Venom!": "Venom",
    "Armed and Dangerous!": "Winter Soldier",
    "Grunts": "Wolverine",
    "Rise, My Friends!": "Adam Warlock",
    "Bast, Grace Us With Victory!": "Black Panther",
    "Mind the Exploding Plasma.": "Black Widow",
    "Together, To Victory!": "Captain America",
    "It’s Co-Op Time!": "Cloak & Dagger",
    "I Unleash the Vishantis’ Power!": "Doctor Strange",
    "We are Groot!": "Groot",
    "Here’s How You Shoot!": "Hawkeye",
    "A Feast for My Crows!": "Hela",
    "My Turn Now!": "Hero Hulk",
    "Now Hulk Mad!": "Hero Hulk",
    "I’m Bright Like a Star!": "Human Torch",
    "Shields Up!": "Invisible Woman",
    "The Dragon Unleashed!": "Iron Fist",
    "Pulse Charge… Fire!": "Iron Man",
    "Yummy, Yummy!": "Jeff the Land Shark",
    "Bring on the Chaos!": "Loki",
    "It’s the Grand Finale!": "Luna Snow",
    "Limbo Stands With You!": "Magik",
    "For Mutantkind!": "Magneto",
    "Friends, Gather Around!": "Mantis",
    "Problem Solved!": "Mister Fantastic",
    "Leave Them to Khonshu.": "Moon Knight",
    "Spider Mode!": "Peni Parker",
    "Watch Me Soar!": "Psylocke",
    "I’m Doing This My Way!": "The Punisher",
    "Hey, Team! Enjoy the Amplifier!": "Rocket Raccoon",
    "The Perfect Hex!": "Scarlet Witch",
    "My Friends Are Here!": "Squirrel Girl",
    "You Get a Web, and You Get a Web, and You Get a Web!": "Spider-Man",
    "Alright!": "Star-Lord",
    "Hurricane Incoming!": "Storm",
    "My Favorite Time!": "The Thing",
    "I Am Asgard’s Might!": "Thor",
    "We Hunger!": "Venom",
    "Stand Down!": "Winter Soldier",
    "Berserker Rage!": "Wolverine"
}
